### ISSUE TITLE
Generate *.strings file should respect uppercase naming

### ISSUE THREAD

**Issue by borut-t** [poviolabs/Lingua#205]
**Describe the bug**
This is how the key is defined in the sheet - `Info_plist`. The generated file is `infoPlist.strings`.

**To Reproduce**
Put the key in spreadsheet and localize it.

**Expected behavior**
The output file should be `InfoPlist.strings`.

**Desktop (please complete the following information):**
 - OS: iOS
 - Version latest

**Comment by EgzonArifi** [comment]
@borut-t with the section key `InfoPlist` , it should generate correctly

**Comment by borut-t** [comment]
Looks like I had the old file in the project. It works 👌
